# application name
spring:
  application:
    name: collect-server
  # Mysql jpa config
  datasource:
    url: jdbc:Mysql://localhost:3306/second_hand?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
        enable_lazy_load_no_trans: true

# server monitor port
server:
  port: 9092

# eureka server cluster
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
