# application name
spring:
  application:
    name: good-server
  # mysql jpa config
  datasource:
    url: jdbc:mysql://localhost:3306/ebook?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true

# server monitor port
server:
  port: 9091

# eureka server cluster
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
