eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
      #defaultZone: http://eureka-server:9000/eureka/
server:
  port: 9001
spring:
  application:
    name: service-demo
