spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 10.79.96.52:9092
          zk-nodes: 10.79.96.52:2182
    config:
      server:
        git:
          searchPaths: config-repo
          uri: https://github.com/LLL4040/Second-hand-trading-web.git
